name: zebra_scanner_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  animated_bottom_navigation_bar: ^1.3.3
  signalr_netcore: ^1.4.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.2
  http: ^1.2.2 
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.5
  flutter_isolate: ^2.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bfx-logo.png